export ZSH="/home/trn/.oh-my-zsh"

ZSH_THEME="af-magic"

plugins=( git zsh-syntax-highlighting zsh-autosuggestions )

source $ZSH/oh-my-zsh.sh

alias s="source ~/.zshrc"
alias n="nano ~/.zshrc"
alias update="sudo apt update"
alias upgrade="sudo apt upgrade"
alias py="python3"
